services:
  laravel_13:
    # Use an image with Apache and PHP pre-installed
    # image: php:8.3-apache
    container_name: laravel_13_vue
    build:
      context: . # Root of the build (where to find files to COPY)
      dockerfile: ./Dockerfile  # Path to the specific file
    volumes:
      # Mount your actual PHP code here
      - ./code:/var/www/html
      - laravel-node-modules:/var/www/html/node_modules
      - laravel-vendor:/var/www/html/vendor
      # - /var/www/html/vendor
      # - /var/www/html/node_modules
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "5173:5173"  # <--- Add this line to map the Vite port
    environment:
      # Nginx-proxy reads this to route traffic
      - VIRTUAL_HOST=laravel_13_vue.local
      - VIRTUAL_PORT=80 
    networks:
      - web_proxy

networks:
  web_proxy:
    external: true

volumes:
  laravel-node-modules:
  laravel-vendor: